version: '3.9'
services:
  app:
    image: madzone/ironfence-app:v1
    container_name: web-ironfence
    build:
      context: .
      dockerfile: ./docker/Dockerfile.octane
      args:
        PHP_VERSION: '8.3-bullseye'
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
    depends_on:
      - redis
    networks:
      - laravel

      # redis
  redis:
    image: redis:latest
    networks:
      - laravel

  search:
    container_name: elasticsearch_search
    image: elasticsearch:7.17.15
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - laravel

# Se necessário, descomente e configure os serviços MariaDB e Kibana

# mariadb:
#   image: mariadb:latest
#   restart: unless-stopped
#   environment:
#     MYSQL_DATABASE: deepdefense2
#     MYSQL_ROOT_PASSWORD: root
#     MYSQL_PASSWORD: root
#     MYSQL_USER: root
#   volumes:
#     - ./.docker/mariadb/dbdata:/var/lib/mysql
#   ports:
#     - "3388:3306"
#   networks:
#     - laravel

# kibana:
#   image: kibana:7.17.15
#   ports:
#     - "5601:5601"
#   environment:
#     ELASTICSEARCH_HOSTS: "http://search:9200"
#   networks:
#     - laravel

networks:
  laravel:
    driver: bridge

volumes:
  redisdata:
    driver: local
  esdata:
    driver: local
